import type { Metadata } from 'next'
import { Inter, Montserrat, Permanent_Marker } from 'next/font/google'
import '@/app/globals.css'
import { ThemeProvider } from '@/contexts/theme-provider'
import { Toaster } from '@/components/ui/sonner'
// import SessionProviderWrapper from '@/app/sesionProviderWrapper'

const inter = Inter({
  variable: '--font-inter',
  fallback: ['sans-serif'],
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

const montserrat = Montserrat({
  variable: '--font-montserrat',
  fallback: ['sans-serif'],
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

const PermanentMarker = Permanent_Marker({
  variable: '--font-permanent-marker',
  fallback: ['sans-serif'],
  display: 'swap',
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'DINO SHOP',
  description: 'Generated by Thang Dino',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${inter.className} ${montserrat.variable} ${PermanentMarker.variable} overflow-x-hidden`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster richColors position='top-right' />
        </ThemeProvider>
      </body>
    </html>
  )
}
